### ISSUE TITLE
FireFox Errors

### ISSUE THREAD

**Issue by MicrobrewMedia** [chrislkeller/projects.chrislkeller.com#1]
When loading with FireFox data is never loaded. 

According to FireBug -
"SyntaxError: syntax error"

"https://spreadsheets.google.com/feeds/worksheets/0ApLwuu1HQNO7dHJVY1dsdWZlT2lNRjZ4eXluY1BWdHc/public/basic?alt=json-in-script&callback=Tabletop.callbacks.tt137382618883958301"

Looks like it is requesting to login to google. I have this issue on a personal project as well as I check on the Demo project.

**Comment by chrislkeller** [comment]
@MicrobrewMedia: I have to apologize for not noticing this issue sooner.

Back around the time you posted there was a bug that affected the way Tabletop.js interacted with Google Sheets. If you hadn't logged in for some time you would get the error you describe. As far as I know this bug has been fixed.
