### ISSUE TITLE
DataTables warning error message

### ISSUE THREAD

**Issue by choltovich** [chrislkeller/projects.chrislkeller.com#3]
Hi Chris,

I am trying to build a data table on the following page: http://christopherholt.net/university-news-table.html

I get this message:

DataTables warning (table id = 'data-table-container'): Requested unknown parameter 'site-name' from the data source for row 0

Do you have any idea what might cause that? It seems to be a common problem, but I can't find a solution. Thanks!

![screen shot 2014-01-18 at 7 45 07 pm](https://f.cloud.github.com/assets/4679260/1959814/70707078-8238-11e3-87e4-9a0b9476cd51.png)

**Comment by thehabdash** [comment]
Same issue. After many different searches and attempts, still receiving the error intermittently. Sometimes it works, and sometimes it doesnt.  Code is here: https://github.com/thehabdash/sdcat

Would love love love if anyone has thoughts on this.
