### ISSUE TITLE
getting /od6/ from Google Spreadsheets

### ISSUE THREAD

**Issue by tylermachado** [chrislkeller/projects.chrislkeller.com#4]
Hi! I am getting a 400 Bad Request message when trying to grab a Google Spreadsheet for use with the Tabletop to Datatables script. Using the default key works fine, but changing the key to any of my spreadsheets gives me the 400 -- even when the spreadsheet is publishing to web and set to public visibility.

The difference I caught is this. Looking at the network tab in my inspector, the functioning demo uses this :path in the request header--

/feeds/list/0An8W63YKWOsxdHlyTVAzQ1RPSGhxZDM5T3NqdU9RcHc/od6/public/values?alt=json-in-script&sq=&callback=Tabletop.callbacks.tt140067863268497459
 
while my failing version uses this :path--

/feeds/list/1Kh42bkbrsnqJJpoYpeOEErGaorWsEfdXFgs62xIe8Ac/csv/public/values?alt=json-in-script&sq=&callback=Tabletop.callbacks.tt140067862391443006

Now obviously the keys are different, but right after the key, the working version has /od6/ while the broken one has /csv/. How do I force Google Spreadsheets to send me back /od6/ instead?

Thanks!

**Comment by chrislkeller** [comment]
@tylermachado: I have apologize but I never noticed this issue until now. Seeing as it's from more than a year ago I'm guessing you either found a solution, another method or moved on.

Either way, if it's still a thing I've not heard of it before. Might be a mix of an older version of tabletop and a newer version of Google Sheets. Do you have code to point me to so I can try to reproduce the error?

Again, apologies for not noticing this earlier. Enjoy #SRCCON.

**Comment by tylermachado** [comment]
omg I totally forgot about this and had no idea that you were the person who developed this! Let me remember how I figured this out 😁
